'use client';

import { MessageThread } from '@/components/chats/message-thread';
import { PageLoading } from '@/components/page-loading';
import { createClient } from '@/lib/supabase/client';
import { contactDisplayName } from '@/lib/contact-colors';
import { useSearchParams } from 'next/navigation';
import { Suspense,useEffect,useState } from 'react';

function ConversationView(){const params=useSearchParams();const id=params.get('id');const[state,setState]=useState<any>(null);useEffect(()=>{if(!id)return;void(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const{data:c}=await s.from('conversations').select(`id,type,group_id,group:groups(id,name),participants:conversation_participants(user_id,profile:profiles(id,display_name,avatar_url))`).eq('id',id).single();if(!c){setState({error:'Conversation not found.'});return;}const{data:messages}=await s.from('messages').select('id,conversation_id,sender_id,body,created_at,edited_at,attachments').eq('conversation_id',id).order('created_at',{ascending:true}).limit(200);await s.rpc('mark_conversation_read',{p_conversation_id:id});const participants=(c as any).participants.filter((participant:any)=>participant.profile);const participantIds=participants.map((participant:any)=>participant.user_id).filter((userId:string)=>userId!==user.id);const{data:preferences}=participantIds.length?await s.from('contact_preferences').select('contact_id,nickname,color_key').eq('owner_id',user.id).in('contact_id',participantIds):{data:[]};const preferencesById=Object.fromEntries((preferences??[]).map((preference:any)=>[preference.contact_id,preference]));const other=participants.find((participant:any)=>participant.user_id!==user.id);const title=c.type==='group'?(c as any).group?.name??'Group':other?contactDisplayName(other.profile,preferencesById[other.user_id]):'Contact';setState({c,userId:user.id,title,messages:messages??[],profiles:Object.fromEntries(participants.map((p:any)=>[p.user_id,p.profile])),preferencesById});})()},[id]);if(!id)return <p className="p-8 text-sm text-red-500">Missing conversation.</p>;if(!state)return <PageLoading/>;if(state.error)return <p className="p-8 text-sm text-red-500">{state.error}</p>;return <MessageThread conversationId={state.c.id} title={state.title} isGroup={state.c.type==='group'} groupId={state.c.group_id} currentUserId={state.userId} participantsById={state.profiles} preferencesById={state.preferencesById} initialMessages={state.messages}/>}
export default function ConversationPage(){return <Suspense fallback={<PageLoading/>}><ConversationView/></Suspense>}
