'use client';

import { PlanHeader } from '@/components/planner/plan-header';
import { PlanInstanceCard } from '@/components/planner/plan-instance-card';
import { PageLoading } from '@/components/page-loading';
import { createClient } from '@/lib/supabase/client';
import { useSearchParams } from 'next/navigation';
import { Suspense,useEffect,useState } from 'react';

function PlanView(){const params=useSearchParams();const id=params.get('id');const[state,setState]=useState<any>(null);useEffect(()=>{if(!id)return;void(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const{data:plan}=await s.from('plans').select(`id,name,notes,response_type,repeat_rule,created_by,starts_on,repeat_until,group:groups(id,name),options:plan_options(id,label,sort_order),instances:plan_instances(id,occurs_on)`).eq('id',id).single();if(!plan){setState({error:'Plan not found.'});return;}const group=(plan as any).group;const instances=[...(plan as any).instances].sort((a:any,b:any)=>a.occurs_on.localeCompare(b.occurs_on));const[{data:members},{data:responses},{data:membership}]=await Promise.all([s.from('group_members').select('user_id,profile:profiles(id,display_name)').eq('group_id',group.id),s.from('plan_responses').select('id,plan_instance_id,user_id,option_id,rsvp_status').in('plan_instance_id',instances.map((i:any)=>i.id)),s.from('group_members').select('role').eq('group_id',group.id).eq('user_id',user.id).single()]);setState({plan,group,instances,options:[...(plan as any).options].sort((a:any,b:any)=>a.sort_order-b.sort_order),members:(members??[]).map((m:any)=>m.profile).filter(Boolean),responses:responses??[],userId:user.id,canDelete:plan.created_by===user.id||membership?.role==='admin'});})()},[id]);if(!id)return <p className="p-8 text-sm text-red-500">Missing plan.</p>;if(!state)return <PageLoading/>;if(state.error)return <p className="p-8 text-sm text-red-500">{state.error}</p>;return <div className="mx-auto max-w-2xl px-4 py-8 md:px-6"><PlanHeader plan={state.plan} groupName={state.group.name} canDelete={state.canDelete}/><div className="mt-6 space-y-6">{state.instances.map((instance:any)=><PlanInstanceCard key={instance.id} instance={instance} responseType={state.plan.response_type} options={state.options} groupMembers={state.members} responses={state.responses.filter((r:any)=>r.plan_instance_id===instance.id)} currentUserId={state.userId}/>)}</div></div>}
export default function PlanDetailPage(){return <Suspense fallback={<PageLoading/>}><PlanView/></Suspense>}
