-- Relay first-run onboarding, usernames, and identity fields.

alter table public.profiles add column if not exists first_name text;
alter table public.profiles add column if not exists last_name text;
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists graduation_year integer;
alter table public.profiles add column if not exists onboarding_completed_at timestamptz;
alter table public.profiles add column if not exists terms_accepted_at timestamptz;
alter table public.profiles add column if not exists privacy_acknowledged_at timestamptz;
alter table public.profiles add column if not exists username_changed_at timestamptz;

do $$
begin
  alter table public.profiles add constraint profiles_first_name_length check (first_name is null or char_length(first_name) between 1 and 40);
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table public.profiles add constraint profiles_last_name_length check (last_name is null or char_length(last_name) between 1 and 60);
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table public.profiles add constraint profiles_username_format check (username is null or username ~ '^[a-z0-9_]{3,20}$');
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table public.profiles add constraint profiles_graduation_year_range check (graduation_year is null or graduation_year between 2000 and 2100);
exception when duplicate_object then null;
end $$;

create unique index if not exists profiles_username_unique
  on public.profiles (lower(username))
  where username is not null;

create table if not exists public.username_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  changed_at timestamptz not null default now()
);

create index if not exists username_history_user_changed_idx
  on public.username_history(user_id, changed_at desc);

alter table public.username_history enable row level security;

drop policy if exists username_history_select_own on public.username_history;
create policy username_history_select_own
  on public.username_history for select
  to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.username_history from anon;
grant select on public.username_history to authenticated;

create schema if not exists private;

create or replace function private.clean_relay_username(p_username text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select lower(trim(leading '@' from trim(coalesce(p_username, ''))));
$$;

create or replace function private.relay_username_reserved(p_username text)
returns boolean
language sql
immutable
set search_path = pg_catalog
as $$
  select lower(coalesce(p_username, '')) = any (array[
    'relay','resonant','admin','administrator','owner','moderator','mod','staff',
    'support','help','security','system','official','team','everyone','here',
    'api','root','null','undefined','settings','account','accounts','contact',
    'contacts','discover','report','reports','mail','calendar','planner','todo'
  ]::text[]);
$$;

create or replace function public.username_available(p_username text)
returns boolean
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  caller uuid := (select auth.uid());
  clean text := private.clean_relay_username(p_username);
begin
  if caller is null then raise exception 'not authenticated'; end if;
  if clean !~ '^[a-z0-9_]{3,20}$' then return false; end if;
  if private.relay_username_reserved(clean) then return false; end if;

  return not exists (
    select 1 from public.profiles p
    where lower(p.username) = clean
      and p.id <> caller
  );
end;
$$;

revoke all on function public.username_available(text) from public;
grant execute on function public.username_available(text) to authenticated;

create or replace function public.save_onboarding_profile(
  p_first_name text,
  p_last_name text,
  p_username text,
  p_school text default null,
  p_graduation_year integer default null,
  p_avatar_url text default null,
  p_discoverable boolean default true,
  p_show_school boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  caller uuid := (select auth.uid());
  clean_first text := trim(coalesce(p_first_name, ''));
  clean_last text := trim(coalesce(p_last_name, ''));
  clean_username text := private.clean_relay_username(p_username);
  clean_school text := nullif(trim(coalesce(p_school, '')), '');
  clean_avatar text := nullif(trim(coalesce(p_avatar_url, '')), '');
  result_row public.profiles%rowtype;
begin
  if caller is null then raise exception 'not authenticated'; end if;
  if char_length(clean_first) < 1 or char_length(clean_first) > 40 then raise exception 'first name must be 1–40 characters'; end if;
  if char_length(clean_last) < 1 or char_length(clean_last) > 60 then raise exception 'last name must be 1–60 characters'; end if;
  if clean_username !~ '^[a-z0-9_]{3,20}$' then raise exception 'username must be 3–20 letters, numbers, or underscores'; end if;
  if private.relay_username_reserved(clean_username) then raise exception 'that username is reserved'; end if;
  if clean_school is not null and char_length(clean_school) > 80 then raise exception 'school must be 80 characters or fewer'; end if;
  if p_graduation_year is not null and (p_graduation_year < extract(year from current_date)::integer - 4 or p_graduation_year > extract(year from current_date)::integer + 12) then
    raise exception 'choose a valid graduation year';
  end if;
  if clean_avatar is not null and (char_length(clean_avatar) > 500 or clean_avatar !~ '^https://') then
    raise exception 'profile photo must use a full HTTPS link';
  end if;
  if exists (select 1 from public.profiles p where lower(p.username) = clean_username and p.id <> caller) then
    raise exception 'username unavailable';
  end if;

  update public.profiles
  set first_name = clean_first,
      last_name = clean_last,
      display_name = clean_first || ' ' || clean_last,
      username = clean_username,
      school = clean_school,
      graduation_year = p_graduation_year,
      avatar_url = coalesce(clean_avatar, avatar_url),
      discoverable_in_contacts = coalesce(p_discoverable, true),
      show_school_in_discovery = coalesce(p_show_school, false) and coalesce(p_discoverable, true),
      updated_at = now()
  where id = caller
  returning * into result_row;

  if result_row.id is null then raise exception 'profile unavailable'; end if;

  return jsonb_build_object(
    'id', result_row.id,
    'display_name', result_row.display_name,
    'first_name', result_row.first_name,
    'last_name', result_row.last_name,
    'username', result_row.username,
    'relay_number', result_row.relay_number,
    'school', result_row.school,
    'graduation_year', result_row.graduation_year,
    'avatar_url', result_row.avatar_url,
    'discoverable_in_contacts', result_row.discoverable_in_contacts,
    'show_school_in_discovery', result_row.show_school_in_discovery
  );
exception
  when unique_violation then raise exception 'username unavailable';
end;
$$;

revoke all on function public.save_onboarding_profile(text,text,text,text,integer,text,boolean,boolean) from public;
grant execute on function public.save_onboarding_profile(text,text,text,text,integer,text,boolean,boolean) to authenticated;

create or replace function public.finish_onboarding(p_accept_terms boolean)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  caller uuid := (select auth.uid());
  result_row public.profiles%rowtype;
begin
  if caller is null then raise exception 'not authenticated'; end if;
  if coalesce(p_accept_terms, false) = false then raise exception 'accept Relay terms and privacy policy to continue'; end if;

  select * into result_row from public.profiles where id = caller for update;
  if result_row.id is null then raise exception 'profile unavailable'; end if;
  if nullif(trim(coalesce(result_row.first_name, '')), '') is null
     or nullif(trim(coalesce(result_row.last_name, '')), '') is null
     or nullif(trim(coalesce(result_row.username, '')), '') is null then
    raise exception 'finish your name and username first';
  end if;

  update public.profiles
  set onboarding_completed_at = coalesce(onboarding_completed_at, now()),
      terms_accepted_at = coalesce(terms_accepted_at, now()),
      privacy_acknowledged_at = coalesce(privacy_acknowledged_at, now()),
      updated_at = now()
  where id = caller
  returning * into result_row;

  return jsonb_build_object(
    'display_name', result_row.display_name,
    'username', result_row.username,
    'relay_number', result_row.relay_number,
    'onboarding_completed_at', result_row.onboarding_completed_at
  );
end;
$$;

revoke all on function public.finish_onboarding(boolean) from public;
grant execute on function public.finish_onboarding(boolean) to authenticated;

create or replace function public.change_username(p_username text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  caller uuid := (select auth.uid());
  clean_username text := private.clean_relay_username(p_username);
  current_row public.profiles%rowtype;
  next_allowed timestamptz;
begin
  if caller is null then raise exception 'not authenticated'; end if;
  if clean_username !~ '^[a-z0-9_]{3,20}$' then raise exception 'username must be 3–20 letters, numbers, or underscores'; end if;
  if private.relay_username_reserved(clean_username) then raise exception 'that username is reserved'; end if;

  select * into current_row from public.profiles where id = caller for update;
  if current_row.id is null then raise exception 'profile unavailable'; end if;
  if lower(coalesce(current_row.username, '')) = clean_username then
    return jsonb_build_object('username', current_row.username, 'changed_at', current_row.username_changed_at);
  end if;

  if current_row.username_changed_at is not null then
    next_allowed := current_row.username_changed_at + interval '14 days';
    if next_allowed > now() then raise exception 'username can be changed again after %', next_allowed; end if;
  end if;

  if exists (select 1 from public.profiles p where lower(p.username) = clean_username and p.id <> caller) then
    raise exception 'username unavailable';
  end if;

  if current_row.username is not null then
    insert into public.username_history(user_id, username) values (caller, current_row.username);
  end if;

  update public.profiles
  set username = clean_username,
      username_changed_at = now(),
      updated_at = now()
  where id = caller
  returning * into current_row;

  return jsonb_build_object('username', current_row.username, 'changed_at', current_row.username_changed_at);
exception
  when unique_violation then raise exception 'username unavailable';
end;
$$;

revoke all on function public.change_username(text) from public;
grant execute on function public.change_username(text) to authenticated;

-- Grandfather all accounts that existed before first-run onboarding launched.
update public.profiles
set first_name = coalesce(first_name, nullif(split_part(trim(display_name), ' ', 1), '')),
    last_name = coalesce(last_name, nullif(trim(substr(trim(display_name), length(split_part(trim(display_name), ' ', 1)) + 1)), '')),
    onboarding_completed_at = coalesce(onboarding_completed_at, now()),
    terms_accepted_at = coalesce(terms_accepted_at, now()),
    privacy_acknowledged_at = coalesce(privacy_acknowledged_at, now()),
    updated_at = now()
where onboarding_completed_at is null;

-- Existing Discover clients keep their original result shape, but name search
-- now also matches usernames (with or without a leading @).
create or replace function public.search_contact_discovery(p_query text, p_limit integer default 12)
returns table(id uuid, display_name text, avatar_url text, school text, mutual_count integer, shared_group_count integer, request_state text)
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  caller uuid := (select auth.uid());
  clean_query text := lower(trim(leading '@' from trim(coalesce(p_query, ''))));
  safe_limit integer := least(greatest(coalesce(p_limit, 12), 1), 20);
  recent_attempts integer;
begin
  if caller is null then raise exception 'not authenticated'; end if;
  if char_length(clean_query) < 2 then raise exception 'enter at least 2 characters'; end if;
  if char_length(clean_query) > 40 then clean_query := left(clean_query, 40); end if;

  select count(*) into recent_attempts
  from public.contact_discovery_attempts a
  where a.requester_id = caller
    and a.created_at > now() - interval '10 minutes';

  if recent_attempts >= 60 then
    raise exception 'too many searches — please wait a few minutes and try again';
  end if;

  insert into public.contact_discovery_attempts (requester_id) values (caller);

  return query
  with my_contacts as (
    select case when c.user_a = caller then c.user_b else c.user_a end as contact_id
    from public.connections c
    where c.user_a = caller or c.user_b = caller
  ),
  my_groups as (
    select gm.group_id
    from public.group_members gm
    where gm.user_id = caller
  ),
  candidates as (
    select
      p.id,
      p.display_name,
      p.avatar_url,
      case when p.show_school_in_discovery then p.school else null end as school,
      p.username,
      (
        select count(*)::integer
        from my_contacts mine
        where exists (
          select 1 from public.connections their_connection
          where (their_connection.user_a = p.id and their_connection.user_b = mine.contact_id)
             or (their_connection.user_b = p.id and their_connection.user_a = mine.contact_id)
        )
      ) as mutual_count,
      (
        select count(*)::integer
        from my_groups mine_group
        join public.group_members their_group
          on their_group.group_id = mine_group.group_id
         and their_group.user_id = p.id
      ) as shared_group_count,
      case
        when exists (
          select 1 from public.connection_requests r
          where r.sender_id = caller and r.recipient_id = p.id and r.status = 'pending'
        ) then 'outgoing'
        when exists (
          select 1 from public.connection_requests r
          where r.sender_id = p.id and r.recipient_id = caller and r.status = 'pending'
        ) then 'incoming'
        else 'none'
      end as request_state
    from public.profiles p
    where p.id <> caller
      and p.discoverable_in_contacts = true
      and (
        position(clean_query in lower(p.display_name)) > 0
        or position(clean_query in lower(coalesce(p.username, ''))) > 0
      )
      and not public.are_connected(caller, p.id)
      and not private.is_blocked_between(caller, p.id)
  )
  select
    c.id,
    c.display_name,
    c.avatar_url,
    c.school,
    c.mutual_count,
    c.shared_group_count,
    c.request_state
  from candidates c
  order by
    case when lower(coalesce(c.username, '')) = clean_query then 0
         when lower(c.display_name) = clean_query then 1
         when left(lower(coalesce(c.username, '')), char_length(clean_query)) = clean_query then 2
         when left(lower(c.display_name), char_length(clean_query)) = clean_query then 3
         else 4 end,
    c.mutual_count desc,
    c.shared_group_count desc,
    lower(c.display_name)
  limit safe_limit;
end;
$$;

revoke all on function public.search_contact_discovery(text, integer) from public;
grant execute on function public.search_contact_discovery(text, integer) to authenticated;
