'use client';

import { ConnectGoogleButton } from '@/components/google/connect-button';
import { DisconnectGoogleButton } from '@/components/google/disconnect-button';
import { PageLoading } from '@/components/page-loading';
import { PageHeader } from '@/components/ui/page-header';
import { createClient } from '@/lib/supabase/client';
import { useEffect,useState } from 'react';

export default function EmailPage(){const[state,setState]=useState<any>(null);useEffect(()=>{void(async()=>{const s=createClient();const{data:status,error}=await s.functions.invoke('google-hub',{body:{action:'status',service:'gmail'}});if(error||!status?.connected){setState({connected:false,messages:[],loadError:false});return;}const r=await s.functions.invoke('google-hub',{body:{action:'gmail_messages',service:'gmail'}});setState({connected:true,messages:r.data?.messages??[],loadError:!!r.error});})()},[]);if(!state)return <PageLoading/>;return <div className="mx-auto max-w-2xl px-4 py-8 md:px-6"><PageHeader title="Email" subtitle="The school email that actually needs your attention." action={state.connected?<DisconnectGoogleButton service="gmail"/>:<ConnectGoogleButton service="gmail" next="/email"/>}/>{!state.connected?<div className="mt-8 rounded-md border border-dashed border-border py-10 text-center"><p className="text-sm text-ink-muted">Connect Gmail to see your inbox here.</p><p className="mt-1 text-xs text-ink-faint">Read-only — Relay never sends email without asking.</p></div>:<div className="mt-6">{state.loadError?<p className="text-sm text-red-500">Couldn&apos;t load your inbox right now.</p>:state.messages.length===0?<p className="text-sm text-ink-faint">Inbox is empty.</p>:<ul className="divide-y divide-border rounded-md border border-border">{state.messages.map((m:any)=><li key={m.id} className="px-3 py-3"><div className="flex items-center justify-between gap-3"><span className={`truncate text-sm text-ink ${m.isUnread?'font-semibold':''}`}>{m.subject}</span>{m.receivedAt&&<span className="shrink-0 text-xs text-ink-faint">{formatDate(m.receivedAt)}</span>}</div><p className="mt-0.5 truncate text-xs text-ink-faint">{m.from.replace(/<.*>/,'').trim()||m.from}</p><p className="mt-1 truncate text-xs text-ink-muted">{m.snippet}</p></li>)}</ul>}</div>}</div>}
function formatDate(raw:string){const d=new Date(raw);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
