'use client';

import { NewPlanDialog } from '@/components/planner/new-plan-dialog';
import { PlanList } from '@/components/planner/plan-list';
import { PageLoading } from '@/components/page-loading';
import { PageHeader } from '@/components/ui/page-header';
import { createClient } from '@/lib/supabase/client';
import { useEffect,useState } from 'react';

export default function PlannerPage(){const[state,setState]=useState<any>(null);useEffect(()=>{void(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return;const{data:memberships}=await s.from('group_members').select('group:groups(id,name)').eq('user_id',user.id);const groups=(memberships??[]).map((m:any)=>m.group).filter(Boolean);const ids=groups.map((g:any)=>g.id);if(!ids.length){setState({groups,plans:[],members:new Map(),responses:new Map()});return;}const{data:plans}=await s.from('plans').select(`id,name,response_type,repeat_rule,created_at,group:groups(id,name),options:plan_options(id,label,sort_order),instances:plan_instances(id,occurs_on)`).in('group_id',ids).order('created_at',{ascending:false});const instanceIds=(plans??[]).flatMap((p:any)=>p.instances.map((i:any)=>i.id));const[{data:responses},{data:allMembers}]=await Promise.all([instanceIds.length?s.from('plan_responses').select('plan_instance_id,user_id').in('plan_instance_id',instanceIds):Promise.resolve({data:[]}),s.from('group_members').select('group_id,user_id').in('group_id',ids)]);const members=new Map<string,number>();for(const m of allMembers??[])members.set(m.group_id,(members.get(m.group_id)??0)+1);const counts=new Map<string,number>();for(const r of responses??[])counts.set(r.plan_instance_id,(counts.get(r.plan_instance_id)??0)+1);setState({groups,plans:plans??[],members,responses:counts});})()},[]);if(!state)return <PageLoading/>;return <div className="mx-auto max-w-2xl px-4 py-8 md:px-6"><PageHeader title="Planner" action={state.groups.length?<NewPlanDialog groups={state.groups}/>:undefined}/>{state.groups.length===0?<div className="mt-8 rounded-md border border-dashed border-border py-14 text-center"><p className="text-sm text-ink-muted">You need a group before you can plan anything.</p><p className="mt-1 text-xs text-ink-faint">Create one from Chats, then come back here.</p></div>:<div className="mt-6"><PlanList plans={state.plans} memberCountByGroup={state.members} responseCountByInstance={state.responses}/></div>}</div>}
