'use client';

import { ConnectGoogleButton } from '@/components/google/connect-button';
import { DisconnectGoogleButton } from '@/components/google/disconnect-button';
import { PageLoading } from '@/components/page-loading';
import { PageHeader } from '@/components/ui/page-header';
import { createClient } from '@/lib/supabase/client';
import { useEffect, useState } from 'react';

export default function CalendarPage() {
  const [state, setState] = useState<any>(null);
  useEffect(() => { void (async () => { const s = createClient(); const { data: { user } } = await s.auth.getUser(); if (!user) return; let connected = false, events: any[] = [], calendarError = false; const { data: status, error } = await s.functions.invoke('google-hub', { body: { action: 'status', service: 'calendar' } }); if (!error && status?.connected) { connected = true; const r = await s.functions.invoke('google-hub', { body: { action: 'calendar_events', service: 'calendar' } }); if (r.error) calendarError = true; else events = r.data?.events ?? []; } const { data: memberships } = await s.from('group_members').select('group_id').eq('user_id', user.id); const groupIds = (memberships ?? []).map((m) => m.group_id); let upcoming: any[] = []; if (groupIds.length) { const { data: plans } = await s.from('plans').select('id,name,group:groups(name),instances:plan_instances(id,occurs_on)').in('group_id', groupIds); const today = new Date().toISOString().slice(0, 10); upcoming = (plans ?? []).flatMap((p: any) => p.instances.filter((i: any) => i.occurs_on >= today).map((i: any) => ({ instanceId: i.id, occursOn: i.occurs_on, planName: p.name, groupName: p.group?.name }))).sort((a: any, b: any) => a.occursOn.localeCompare(b.occursOn)).slice(0, 10); } setState({ connected, events, calendarError, upcoming }); })(); }, []);
  if (!state) return <PageLoading />;
  return <div className="mx-auto max-w-2xl px-4 py-8 md:px-6"><PageHeader title="Calendar" subtitle="Everything happening, with Relay plans kept close by." action={state.connected ? <DisconnectGoogleButton service="calendar" /> : <ConnectGoogleButton service="calendar" next="/calendar" />} />{!state.connected && <div className="mt-8 rounded-md border border-dashed border-border py-10 text-center"><p className="text-sm text-ink-muted">Connect Google Calendar to see your full upcoming schedule here.</p><p className="mt-1 text-xs text-ink-faint">Relay only requests read access to your events.</p></div>}{state.connected && <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs uppercase tracking-wide text-ink-faint">Your schedule</p><h2 className="mt-1 text-lg font-medium text-ink">Up next</h2></div><span className="text-xs text-ink-faint">{state.events.length} event{state.events.length === 1 ? '' : 's'}</span></div>{state.calendarError ? <p className="text-sm text-red-500">Couldn&apos;t load your calendar right now.</p> : state.events.length === 0 ? <p className="rounded-md border border-border px-3 py-6 text-sm text-ink-faint">Nothing coming up.</p> : <ul className="divide-y divide-border rounded-md border border-border">{state.events.map((e: any) => <li key={e.id} className="flex items-start justify-between gap-4 px-3 py-3"><div><p className="text-sm font-medium text-ink">{e.summary}</p><p className="mt-1 text-xs text-ink-muted">{formatEvent(e.start, e.isAllDay)}{e.end && ` · until ${formatEvent(e.end, e.isAllDay)}`}</p></div>{e.htmlLink && <a href={e.htmlLink} target="_blank" rel="noreferrer" className="shrink-0 text-xs text-ink-faint underline underline-offset-4">Open</a>}</li>)}</ul>}</section>}<section className="mt-8"><div className="mb-3"><p className="text-xs uppercase tracking-wide text-ink-faint">Relay planning</p><h2 className="mt-1 text-lg font-medium text-ink">Group stuff</h2></div>{state.upcoming.length === 0 ? <p className="text-sm text-ink-faint">No upcoming plans.</p> : <ul className="divide-y divide-border rounded-md border border-border">{state.upcoming.map((p: any) => <li key={p.instanceId} className="flex items-center justify-between px-3 py-2.5"><div><span className="text-sm text-ink">{p.planName}</span><span className="ml-2 text-xs text-ink-faint">{p.groupName}</span></div><span className="text-xs text-ink-faint">{new Date(`${p.occursOn}T00:00:00`).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</span></li>)}</ul>}</section></div>;
}

function formatEvent(start: string, allDay: boolean) { const d = new Date(start); return allDay ? d.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' }) : d.toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
