'use client';

import { PageLoading } from '@/components/page-loading';
import { PageHeader } from '@/components/ui/page-header';
import { createClient } from '@/lib/supabase/client';
import { CalendarDays, Plus, RefreshCw, X } from 'lucide-react';
import { useEffect, useState } from 'react';

type Provider = 'google' | 'microsoft';
type Account = { id: string; provider: Provider; email_address: string; display_name: string | null; granted_scope: string };

export default function CalendarPage() {
  const [state, setState] = useState<any>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { void load(); }, []);
  async function load() { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const [accountResult, eventResult, membershipResult] = await Promise.all([supabase.functions.invoke('mail-hub', { body: { action: 'accounts' } }), supabase.functions.invoke('mail-hub', { body: { action: 'calendar_events' } }), supabase.from('group_members').select('group_id').eq('user_id', user.id)]); const groupIds = (membershipResult.data ?? []).map((membership) => membership.group_id); let upcoming: any[] = []; if (groupIds.length) { const { data: plans } = await supabase.from('plans').select('id,name,group:groups(name),instances:plan_instances(id,occurs_on)').in('group_id', groupIds); const today = new Date().toISOString().slice(0, 10); upcoming = (plans ?? []).flatMap((plan: any) => plan.instances.filter((instance: any) => instance.occurs_on >= today).map((instance: any) => ({ instanceId: instance.id, occursOn: instance.occurs_on, planName: plan.name, groupName: plan.group?.name }))).sort((a: any, b: any) => a.occursOn.localeCompare(b.occursOn)).slice(0, 10); } setState({ accounts: accountResult.data?.accounts ?? [], events: eventResult.data?.events ?? [], accountErrors: eventResult.data?.accountErrors ?? [], upcoming }); if (accountResult.error || eventResult.error) setError('Some calendar data could not load.'); }
  async function connect(provider: Provider) { setBusy(provider); setError(null); const { data, error: invokeError } = await createClient().functions.invoke('mail-hub', { body: { action: 'connect_start', provider, next: '/calendar' } }); if (invokeError || !data?.url) { setError(data?.error ?? `${provider === 'google' ? 'Google' : 'Microsoft'} OAuth is not configured yet.`); setBusy(null); return; } window.location.assign(data.url); }
  async function disconnect(account: Account) { if (!confirm(`Disconnect ${account.email_address} from Relay email and calendar?`)) return; setBusy(account.id); const { error: invokeError } = await createClient().functions.invoke('mail-hub', { body: { action: 'disconnect', accountId: account.id } }); if (invokeError) { setError('Could not disconnect that account.'); setBusy(null); return; } await load(); setBusy(null); }
  if (!state) return <PageLoading />;

  return <div className="mx-auto max-w-3xl px-4 py-8 md:px-6"><PageHeader title="Calendar" subtitle="Google, Microsoft, and Relay plans together." />
    <section className="mt-6 rounded-lg border border-border bg-surface-raised p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-medium text-ink">Calendar accounts</h2><p className="mt-0.5 text-xs text-ink-faint">{state.accounts.length} of 3 connected · calendar and inbox are read-only</p></div><CalendarDays size={18} className="text-ink-faint" /></div>{state.accounts.length > 0 && <ul className="mt-4 space-y-2">{state.accounts.map((account: Account) => { const needsReconnect = state.accountErrors.includes(account.email_address); return <li key={account.id} className="flex items-center gap-3 rounded-md bg-surface px-3 py-2.5"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-semibold ${account.provider === 'google' ? 'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300' : 'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300'}`}>{account.provider === 'google' ? 'G' : 'M'}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-ink">{account.email_address}</p><p className={`text-xs ${needsReconnect ? 'text-amber-600' : 'text-ink-faint'}`}>{needsReconnect ? 'Reconnect to grant calendar access' : `${account.provider} calendar connected`}</p></div>{needsReconnect && <button type="button" disabled={Boolean(busy)} onClick={() => void connect(account.provider)} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted" aria-label={`Reconnect ${account.email_address}`}><RefreshCw size={14} /></button>}<button type="button" disabled={busy === account.id} onClick={() => void disconnect(account)} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-faint" aria-label={`Disconnect ${account.email_address}`}><X size={15} /></button></li>; })}</ul>}{state.accounts.length < 3 && <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={Boolean(busy)} onClick={() => void connect('google')} className="inline-flex items-center gap-2 rounded-md bg-ink px-3.5 py-2.5 text-sm font-medium text-canvas disabled:opacity-40"><Plus size={15} />Add Google</button><button type="button" disabled={Boolean(busy)} onClick={() => void connect('microsoft')} className="inline-flex items-center gap-2 rounded-md border border-border px-3.5 py-2.5 text-sm font-medium text-ink hover:bg-surface disabled:opacity-40"><Plus size={15} />Add Microsoft</button></div>}{error && <p className="mt-3 text-xs text-red-500">{error}</p>}</section>
    <section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs uppercase tracking-wide text-ink-faint">Every connected calendar</p><h2 className="mt-1 text-lg font-medium text-ink">Up next</h2></div><span className="text-xs text-ink-faint">{state.events.length} events</span></div>{state.events.length === 0 ? <p className="rounded-md border border-border px-3 py-6 text-sm text-ink-faint">No upcoming events. If an older account is connected, reconnect it once to grant calendar access.</p> : <ul className="divide-y divide-border rounded-md border border-border">{state.events.map((event: any) => <li key={event.id} className="flex items-start justify-between gap-4 px-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-ink">{event.summary}</p><p className="mt-1 text-xs text-ink-muted">{formatEvent(event.start, event.isAllDay)}{event.end && ` · until ${formatEvent(event.end, event.isAllDay)}`}</p><p className="mt-1 truncate text-[11px] text-ink-faint">{event.accountEmail}</p></div>{event.htmlLink && <a href={event.htmlLink} target="_blank" rel="noreferrer" className="shrink-0 text-xs text-ink-faint underline underline-offset-4">Open</a>}</li>)}</ul>}</section>
    <section className="mt-8"><div className="mb-3"><p className="text-xs uppercase tracking-wide text-ink-faint">Relay planning</p><h2 className="mt-1 text-lg font-medium text-ink">Group plans</h2></div>{state.upcoming.length === 0 ? <p className="text-sm text-ink-faint">No upcoming plans.</p> : <ul className="divide-y divide-border rounded-md border border-border">{state.upcoming.map((plan: any) => <li key={plan.instanceId} className="flex items-center justify-between px-3 py-2.5"><div><span className="text-sm text-ink">{plan.planName}</span><span className="ml-2 text-xs text-ink-faint">{plan.groupName}</span></div><span className="text-xs text-ink-faint">{new Date(`${plan.occursOn}T00:00:00`).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</span></li>)}</ul>}</section>
  </div>;
}

function formatEvent(start: string, allDay: boolean) { const date = new Date(start); return allDay ? date.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' }) : date.toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
