import { appPageUrl } from '@/lib/config';

export default function PrivacyPage() {
  return <LegalPage title="Relay Privacy Policy" effective="September 3, 2026">
    <p>Relay is a private communication and planning app. This policy explains what Relay handles, why it is used, and the controls available to you.</p>
    <h2>Information Relay handles</h2><p>Relay stores account and profile information, contacts and groups, chat messages, reactions, reports, tasks, plans, notification settings, and files you choose to upload. When you connect Google or Microsoft, Relay stores the OAuth credentials needed to maintain that connection and reads the inbox and calendar metadata shown in the app, such as sender, subject, preview, event title, and time. Relay does not ask for permission to send email or change calendar events.</p>
    <h2>How information is used</h2><p>Information is used only to provide Relay features, secure accounts, synchronize connected services, deliver notifications, investigate abuse reports, and maintain the service. Relay does not sell personal information or use connected email or calendar data for advertising.</p>
    <h2>Service providers</h2><p>Relay relies on Supabase for authentication, database, file storage, realtime updates, and backend functions; GitHub Pages for the web app; and Google or Microsoft only when you connect those accounts. Those providers process data under their own terms and privacy policies.</p>
    <h2>Visibility</h2><p>Messages and chat files are visible to members of that conversation. Profile information is visible where needed for contacts, requests, and shared groups. Reports are visible to the reporter and Relay&apos;s moderation systems, not the reported person.</p>
    <h2>Retention and deletion</h2><p>Relay keeps data while your account exists or as needed to operate and protect the service. Unsent messages and their files are deleted from active storage. You can disconnect an email account, download your Relay data, or permanently delete your account in Profile. Limited copies may remain temporarily in provider backups or security logs.</p>
    <h2>Your choices</h2><p>You can edit your profile, mute conversations, manage notifications, delete messages for yourself, unsend recent messages, disconnect external accounts, export your data, and delete your Relay account. You can revoke Google or Microsoft access from those providers&apos; account-security pages too.</p>
    <h2>Young users and school communities</h2><p>Relay should be used with any permission required by your parent, guardian, school, or local law. Do not upload highly sensitive information. Relay is not presented as an official school service unless your school separately says so.</p>
    <h2>Changes and questions</h2><p>This policy may be updated as Relay changes. The effective date above will change when material revisions are published. For a privacy request, use the account controls in Relay or contact the person who provided your Relay access.</p>
  </LegalPage>;
}

function LegalPage({ title, effective, children }: { title: string; effective: string; children: React.ReactNode }) { return <main className="min-h-screen bg-canvas px-5 py-10"><article className="mx-auto max-w-2xl"><a href={appPageUrl('/')} className="text-sm text-ink-muted hover:text-ink">← Relay</a><h1 className="mt-8 font-display text-3xl font-medium tracking-tight text-ink">{title}</h1><p className="mt-2 text-xs text-ink-faint">Effective {effective}</p><div className="legal-copy mt-8 space-y-5 text-sm leading-7 text-ink-muted">{children}</div><footer className="mt-10 border-t border-border pt-5 text-xs text-ink-faint"><a href={appPageUrl('/terms')} className="underline underline-offset-4">Terms of Use</a></footer></article></main>; }
